% Konstruktor der Klasse OmicsData
%
% O = OmicsData(file_or_data, name)
%
%   file_or_data    1) filename: file to be read, if the respecitve
%                   workspace *.mat is available, it is read instead!
% 
%                   2) struct: as generated by OmicsStruct.m 
%                   Can be used to convert deprecated objects from
%                   workspaces
% 
%                   3) data: a matrix used as data
% 
%                   4) Empty: an empty object is initialized
%   
%   name    Name of the project
%
%
%   Examples:
%   O = OmicsData;   % empty Object
% 
% file = 'proteinGroups.txt';
% O = OmicsData(file)

function O = OmicsData(file_or_data, name)
if ~exist('name','var') || isempty(name)
    name = '';
end

if(~exist('file_or_data','var') || isempty(file_or_data))  % load default data set
    O = OmicsData(OmicsStruct);  % empty class
    
elseif(isstruct(file_or_data)) % Conversion of struct to @OmicsData
    % An appropriate struct is provided and converted to the class.
    % This is important if the class field changes and old structs should
    % be converted to new ones (by a proper function).
    Ostruct = file_or_data;
    try
        O = class(Ostruct,'OmicsData');   %
    catch ERR
        warning('The struct cannot be converted to @OmicsData. Choose the struct as shown in function OmicsStruct.m')
        rethrow(ERR);
    end
elseif(isnumeric(file_or_data)) % Falls Datenmatrix �bergeben wurde oder Gr��e einer Matrix (f�r Zufallsdaten)
    data = file_or_data;
    Ostruct = OmicsStruct;
    Ostruct.data.(Ostruct.config.default_data) = data;
    O = OmicsData(Ostruct);
    
else  % filename for reading
    file = file_or_data;
    %     w = which('OmicsData');
    
    [pfad,filename,ext] = fileparts(file);
    if isempty(pfad)
        [pfad,filename,ext] = fileparts(which(file));
    end
    matfile = [pfad,filesep,filename,'.mat'];
    
    if exist(matfile,'file')
        fprintf('Load data from %s (if not intended remove/rename this workspace).\n',matfile);
        tmp = load(matfile);
        data = tmp.data;
        rownames = tmp.rownames;
        colnames = tmp.colnames;
        default_data = tmp.default_data;
    else
        % Read data here
        fprintf('Read data from: %s ...\n',file);
        [data, rownames] = OmicsReadDataMaxQuant(file);
        %save tmp
        [data, rownames, colnames,default_data] = OmicsData2Datamatrix(data,rownames);
        save(matfile,'data','rownames','colnames','default_data');
        fprintf('Save data to %s ...\n',matfile);
    end
    
    
    if(isempty(filename)) % falls []
        filename = '';
    end
    
    
    O = OmicsStruct;
    O.name  = filename;
    O.info.path = file;
    O.data = data;
    O.cols = rownames; % rownames are columns
    O.rows.SampleNames = colnames; % columnnames are rows
    if exist('default_data','var');
        O.config.default_data = default_data;
    end
    
    O = class(O,'OmicsData');
    
end

O = OmicsCheck(O);  % Check the class and add missing properties

