% Konstruktor der Klasse OmicsData
%
% O = OmicsData(file_or_data, name)
%
%   file_or_data    1) filename: file to be read, if the respecitve
%                   workspace *.mat is available, it is read instead!
% 
%                   2) struct: as generated by OmicsStruct.m 
%                   Can be used to convert deprecated objects from
%                   workspaces
% 
%                   3) data: a matrix used as data
% 
%                   4) Empty: an empty object is initialized
%   
%   name    Name of the project
% 
%   forceRead   forces reading the data file (instead of the *.mat
%   workspace)
%
%
%   Examples:
%   O = OmicsData;   % empty Object
% 
% file = 'proteinGroups.txt';
% O = OmicsData(file)

function O = OmicsData(file_or_data, name, forceRead)
if ~exist('name','var') || isempty(name)
    name = '';
end
if ~exist('forceRead','var') || isempty(forceRead)
    forceRead = false;
end

if(~exist('file_or_data','var') || isempty(file_or_data))  % load default data set
    O = OmicsData(OmicsStruct);  % empty class
    
elseif(isstruct(file_or_data)) % Conversion of struct to @OmicsData
    % An appropriate struct is provided and converted to the class.
    % This is important if the class field changes and old structs should
    % be converted to new ones (by a proper function).
    Ostruct = file_or_data;
    try
        O = class(Ostruct,'OmicsData');   %
    catch ERR
        warning('The struct cannot be converted to @OmicsData. Choose the struct as shown in function OmicsStruct.m')
        rethrow(ERR);
    end
elseif(isnumeric(file_or_data)) % Falls Datenmatrix �bergeben wurde oder Gr��e einer Matrix (f�r Zufallsdaten)
    data = file_or_data;
    Ostruct = OmicsStruct;
    Ostruct.data.(Ostruct.config.default_data) = data;
    Ostruct.info.path = name;
    O = OmicsData(Ostruct);
    
else  % filename for reading
    file = file_or_data;
    %     w = which('OmicsData');
    
    [pfad,filename,ext] = fileparts(file);
    if isempty(pfad)
        [pfad,filename,ext] = fileparts(which(file));
    end
    matfile = [pfad,filesep,filename,'.mat'];
    
    if exist(matfile,'file')  && ~forceRead
        fprintf('Load data from %s (if not intended remove/rename this workspace or set forceRead=1).\n',matfile);
        tmp = load(matfile);
        data = tmp.data;
        if isfield(tmp,'rownames')
            rownames = tmp.rownames;
        end
        if isfield(tmp,'colnames')
            colnames = tmp.colnames;
        end
        if isfield(tmp,'default_data')
            default_data = tmp.default_data;
        else
            default_data = data;
        end
    else
        % Read data here
        fprintf('Read data from: %s ...\n',file);
%         raw = OmicsReadData(file);                   % I separated OmicsReadDataMaxQuant to OmicsReadData and OmicsData2Struct, so I can use OmicsReadData for copying peptides.txt to peptidesImp.txt
%         [data, rownames] = OmicsData2Struct(raw);    
        [data, rownames] = OmicsReadDataMaxQuant(file);
        [data, rownames, colnames,default_data] = OmicsData2Datamatrix(data,rownames);
        save(matfile,'data','rownames','colnames','default_data');
        fprintf('Save data to %s ...\n',matfile);
    end
    
    
    if(isempty(filename)) % falls []
        filename = '';
    end
    
    
    O = OmicsStruct;
    O.name  = name; % this is the user-defined name of the data object, not necessarily the filename
    O.info.path = file;
    O.info.filename = filename;
    O.data = data;
    if exist('rownames','var')
        O.cols = rownames; % rownames are a column
    end
    if exist('colnames','var')
        O.rows.SampleNames = colnames; % columnnames are a row
    end
    if exist('default_data','var')
        O.config.default_data = default_data;
    end
    
    O = class(O,'OmicsData');
    
end

O = OmicsCheck(O);  % Check the class and add missing properties

